# Copy into ~/.zprofile
export PATH=$PATH:~/bin:.

# ALIASES
alias fin='say "Command finished, 任务完成了"'
alias hal='say "what do you think you''re doing, dave?"'
alias hey='say "嘿哟"'
alias curse='say "哎呦我的妈啊"'
