---
- hosts: localhost
  tasks:
    - name: Modify .bashrc
      lineinfile: >
        dest=~/.bashrc
        line='. ~/.bash_custom'

    - name: Copy .bash_custom
      copy: >
        src=bash_custom.sh
        dest=~/.bash_custom

    - name: Install common GUI programs
      apt: pkg={{item}}
      sudo: yes
      with_items:
      - synaptic
      - git-cola
      - gimp
      - vlc
      - filezilla
      # - pidgin
      # - calibre
      # - keepassx

    - name: Install common dev tools
      apt: pkg={{item}}
      sudo: yes
      with_items:
      - git
      - curl
      - imagemagick
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev

    - name: Install essential Python tools
      pip: name={{item}}
      sudo: yes
      with_items:
      - virtualenvwrapper
      - grin

    - name: Install audio tools
      include: audio.yml
