---
- hosts: localhost
  tasks:
    - name: Modify .bashrc
      lineinfile: >
        dest=~/.bashrc
        line='. ~/.bash_custom'

    - name: Copy .bash_custom
      copy: >
        src=bash_custom.sh
        dest=~/.bash_custom

    - name: Install common GUI programs
      apt: pkg={{item}}
      become: yes
      with_items:
      - synaptic
      - gimp
      - vlc
      - filezilla
      - keepassx
      # - calibre

    - name: Install common dev tools
      apt: pkg={{item}}
      become: yes
      with_items:
      - imagemagick
      - ffmpeg
      - xclip
      - atomicparsley

    - name: Install essential Python tools
      pip: name={{item}}
      become: yes
      with_items:
      - virtualenvwrapper
      - grin
